server:
  port: 8081

spring:
  cloud:
    stream:
      kafka:
        binder:
            brokers: '127.0.0.1:9092'
            zkNodes: 'zookeeper:2181'
      bindings:
        recipient-save:
          destination: recipient-save
          content-type: application/json
          partitionCount: 20
        group-save:
          destination: group-save
          content-type: application/json
          partitionCount: 20
