server:
  port: 8082

spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: '127.0.0.1:9092'
                    zkNodes: 'zookeeper:2181'
        bindings:
            group-save:
                destination: groups   
                content-type: application/json
                partitionCount: 20
    datasource:
        url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect  
